# Generated by Django 4.1.10 on 2023-08-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalali', '0002_location_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dalali.property'),
        ),
    ]
